"""Create the complete MVP v0.1 database schema.

Revision ID: 20260810_0001
Revises: None
Create Date: 2026-08-10
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "20260810_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('external_auth_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('external_auth_id', name=op.f('uq_users_external_auth_id'))
    )
    op.create_table('assets',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=24), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('IMAGE', 'AUDIO', 'BACKGROUND', 'PROP', 'EVENT', 'ENDING')", name=op.f('ck_assets_asset_type_values')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_assets_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_owner_user_id'), 'assets', ['owner_user_id'], unique=False)
    op.create_table('character_templates',
    sa.Column('creator_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='PRIVATE', nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('PRIVATE', 'UNLISTED', 'PUBLIC')", name=op.f('ck_character_templates_visibility_values')),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], name=op.f('fk_character_templates_creator_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_version_id'], ['character_versions.id'], name='fk_character_templates_current_version_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_templates'))
    )
    op.create_index(op.f('ix_character_templates_creator_user_id'), 'character_templates', ['creator_user_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('creator_user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('PRACTICE', 'SCENARIO', 'TALK')", name=op.f('ck_scenarios_mode_values')),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name=op.f('ck_scenarios_status_values')),
    sa.CheckConstraint('schema_version > 0', name=op.f('ck_scenarios_positive_schema_version')),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], name=op.f('fk_scenarios_creator_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_index(op.f('ix_scenarios_creator_user_id'), 'scenarios', ['creator_user_id'], unique=False)
    op.create_table('character_versions',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('concept_prompt', sa.String(length=200), nullable=False),
    sa.Column('traits_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('speech_style_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('relationship_defaults_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('additional_prompt', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(concept_prompt) BETWEEN 50 AND 200', name=op.f('ck_character_versions_concept_prompt_length')),
    sa.CheckConstraint('version > 0', name=op.f('ck_character_versions_positive_version')),
    sa.ForeignKeyConstraint(['template_id'], ['character_templates.id'], name=op.f('fk_character_versions_template_id_character_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_versions')),
    sa.UniqueConstraint('template_id', 'version', name=op.f('uq_character_versions_template_id'))
    )
    op.create_index(op.f('ix_character_versions_template_id'), 'character_versions', ['template_id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('PRACTICE', 'SCENARIO', 'TALK')", name=op.f('ck_conversations_mode_values')),
    sa.CheckConstraint("status IN ('ACTIVE', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'ARCHIVED')", name=op.f('ck_conversations_status_values')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_conversations_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('scenario_characters',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('character_template_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_role', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['character_template_id'], ['character_templates.id'], name=op.f('fk_scenario_characters_character_template_id_character_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_characters_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_characters')),
    sa.UniqueConstraint('scenario_id', 'character_template_id', name='uq_scenario_characters_template'),
    sa.UniqueConstraint('scenario_id', 'display_order', name='uq_scenario_characters_order')
    )
    op.create_index(op.f('ix_scenario_characters_character_template_id'), 'scenario_characters', ['character_template_id'], unique=False)
    op.create_index(op.f('ix_scenario_characters_scenario_id'), 'scenario_characters', ['scenario_id'], unique=False)
    op.create_table('scenario_endings',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ending_asset_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ending_asset_id'], ['assets.id'], name=op.f('fk_scenario_endings_ending_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_endings_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_endings')),
    sa.UniqueConstraint('scenario_id', 'title', name=op.f('uq_scenario_endings_scenario_id'))
    )
    op.create_index(op.f('ix_scenario_endings_scenario_id'), 'scenario_endings', ['scenario_id'], unique=False)
    op.create_table('scenario_scenes',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('background_asset_id', sa.Uuid(), nullable=True),
    sa.Column('scene_config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('sequence >= 0', name=op.f('ck_scenario_scenes_nonnegative_sequence')),
    sa.ForeignKeyConstraint(['background_asset_id'], ['assets.id'], name=op.f('fk_scenario_scenes_background_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_scenes_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_scenes')),
    sa.UniqueConstraint('scenario_id', 'sequence', name=op.f('uq_scenario_scenes_scenario_id'))
    )
    op.create_index(op.f('ix_scenario_scenes_scenario_id'), 'scenario_scenes', ['scenario_id'], unique=False)
    op.create_table('character_assets',
    sa.Column('character_template_id', sa.Uuid(), nullable=False),
    sa.Column('character_version_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('asset_role', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_character_assets_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_template_id'], ['character_templates.id'], name=op.f('fk_character_assets_character_template_id_character_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_version_id'], ['character_versions.id'], name=op.f('fk_character_assets_character_version_id_character_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_assets')),
    sa.UniqueConstraint('character_template_id', 'asset_id', 'asset_role', name=op.f('uq_character_assets_character_template_id'))
    )
    op.create_index(op.f('ix_character_assets_asset_id'), 'character_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_character_assets_character_template_id'), 'character_assets', ['character_template_id'], unique=False)
    op.create_table('character_instances',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('nickname_override', sa.String(length=100), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['character_templates.id'], name=op.f('fk_character_instances_template_id_character_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_character_instances_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['character_versions.id'], name=op.f('fk_character_instances_version_id_character_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_instances')),
    sa.UniqueConstraint('user_id', 'template_id', name=op.f('uq_character_instances_user_id'))
    )
    op.create_index(op.f('ix_character_instances_template_id'), 'character_instances', ['template_id'], unique=False)
    op.create_index(op.f('ix_character_instances_user_id'), 'character_instances', ['user_id'], unique=False)
    op.create_index(op.f('ix_character_instances_version_id'), 'character_instances', ['version_id'], unique=False)
    op.create_table('motion_profiles',
    sa.Column('character_version_id', sa.Uuid(), nullable=False),
    sa.Column('motion_map_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('renderer_config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_version_id'], ['character_versions.id'], name=op.f('fk_motion_profiles_character_version_id_character_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_motion_profiles'))
    )
    op.create_index(op.f('ix_motion_profiles_character_version_id'), 'motion_profiles', ['character_version_id'], unique=True)
    op.create_table('scenario_runs',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('ending_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='RUNNING', nullable=False),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('RUNNING', 'COMPLETED', 'CANCELLED')", name=op.f('ck_scenario_runs_status_values')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_scenario_runs_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ending_id'], ['scenario_endings.id'], name=op.f('fk_scenario_runs_ending_id_scenario_endings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_runs_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scenario_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_runs')),
    sa.UniqueConstraint('conversation_id', name=op.f('uq_scenario_runs_conversation_id'))
    )
    op.create_index(op.f('ix_scenario_runs_scenario_id'), 'scenario_runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_runs_user_id'), 'scenario_runs', ['user_id'], unique=False)
    op.create_table('scenario_turns',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('scenario_character_id', sa.Uuid(), nullable=True),
    sa.Column('screen_description', sa.Text(), nullable=False),
    sa.Column('character_line', sa.Text(), nullable=True),
    sa.Column('user_input_type', sa.String(length=16), nullable=False),
    sa.Column('evaluation_rule_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('branch_rule_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('image_asset_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("user_input_type IN ('VOICE', 'TEXT', 'CHOICE', 'NONE')", name=op.f('ck_scenario_turns_user_input_type_values')),
    sa.CheckConstraint('sequence >= 0', name=op.f('ck_scenario_turns_nonnegative_sequence')),
    sa.ForeignKeyConstraint(['image_asset_id'], ['assets.id'], name=op.f('fk_scenario_turns_image_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_character_id'], ['scenario_characters.id'], name=op.f('fk_scenario_turns_scenario_character_id_scenario_characters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenario_scenes.id'], name=op.f('fk_scenario_turns_scene_id_scenario_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_turns')),
    sa.UniqueConstraint('scene_id', 'sequence', name=op.f('uq_scenario_turns_scene_id'))
    )
    op.create_index(op.f('ix_scenario_turns_scene_id'), 'scenario_turns', ['scene_id'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('character_version_id', sa.Uuid(), nullable=False),
    sa.Column('provider_key', sa.String(length=50), nullable=True),
    sa.Column('provider_voice_id', sa.String(length=255), nullable=True),
    sa.Column('style_defaults_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sample_asset_uri', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_version_id'], ['character_versions.id'], name=op.f('fk_voice_profiles_character_version_id_character_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_profiles'))
    )
    op.create_index(op.f('ix_voice_profiles_character_version_id'), 'voice_profiles', ['character_version_id'], unique=True)
    op.create_table('adaptation_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('character_instance_id', sa.Uuid(), nullable=False),
    sa.Column('preferences_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('supporting_session_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('supporting_session_count >= 0', name=op.f('ck_adaptation_profiles_nonnegative_session_count')),
    sa.ForeignKeyConstraint(['character_instance_id'], ['character_instances.id'], name=op.f('fk_adaptation_profiles_character_instance_id_character_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_adaptation_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adaptation_profiles')),
    sa.UniqueConstraint('user_id', 'character_instance_id', name=op.f('uq_adaptation_profiles_user_id'))
    )
    op.create_index(op.f('ix_adaptation_profiles_character_instance_id'), 'adaptation_profiles', ['character_instance_id'], unique=False)
    op.create_index(op.f('ix_adaptation_profiles_user_id'), 'adaptation_profiles', ['user_id'], unique=False)
    op.create_table('character_relationships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('character_instance_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('closeness', sa.Numeric(precision=6, scale=3), server_default='0', nullable=False),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_instance_id'], ['character_instances.id'], name=op.f('fk_character_relationships_character_instance_id_character_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_character_relationships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_relationships')),
    sa.UniqueConstraint('user_id', 'character_instance_id', name=op.f('uq_character_relationships_user_id'))
    )
    op.create_index(op.f('ix_character_relationships_character_instance_id'), 'character_relationships', ['character_instance_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_user_id'), 'character_relationships', ['user_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('character_instance_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('participant_role', sa.String(length=50), server_default='ACTIVE', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_conversation_participants_nonnegative_display_order')),
    sa.ForeignKeyConstraint(['character_instance_id'], ['character_instances.id'], name=op.f('fk_conversation_participants_character_instance_id_character_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_participants_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'character_instance_id', name=op.f('pk_conversation_participants')),
    sa.UniqueConstraint('conversation_id', 'display_order', name=op.f('uq_conversation_participants_conversation_id'))
    )
    op.create_table('memory_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('memory_type', sa.String(length=24), nullable=False),
    sa.Column('owner_character_instance_id', sa.Uuid(), nullable=True),
    sa.Column('source_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sensitivity', sa.String(length=16), server_default='PERSONAL', nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(memory_type IN ('RELATIONSHIP', 'CHARACTER_INTERNAL') AND owner_character_instance_id IS NOT NULL) OR (memory_type IN ('USER_GLOBAL', 'GROUP') AND owner_character_instance_id IS NULL)", name=op.f('ck_memory_items_owner_matches_memory_type')),
    sa.CheckConstraint("memory_type IN ('USER_GLOBAL', 'RELATIONSHIP', 'GROUP', 'CHARACTER_INTERNAL')", name=op.f('ck_memory_items_memory_type_values')),
    sa.CheckConstraint("sensitivity IN ('PUBLIC', 'PERSONAL', 'PRIVATE', 'HIGH')", name=op.f('ck_memory_items_sensitivity_values')),
    sa.ForeignKeyConstraint(['owner_character_instance_id'], ['character_instances.id'], name=op.f('fk_memory_items_owner_character_instance_id_character_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], name=op.f('fk_memory_items_source_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memory_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_items'))
    )
    op.create_index(op.f('ix_memory_items_user_id'), 'memory_items', ['user_id'], unique=False)
    op.create_index('ix_memory_items_user_type', 'memory_items', ['user_id', 'memory_type'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_type', sa.String(length=16), nullable=False),
    sa.Column('speaker_user_id', sa.Uuid(), nullable=True),
    sa.Column('speaker_character_instance_id', sa.Uuid(), nullable=True),
    sa.Column('scene_plan_id', sa.Uuid(), nullable=True),
    sa.Column('scene_turn_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_mode', sa.String(length=16), nullable=False),
    sa.Column('finalized', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('interrupted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(speaker_type = 'USER' AND speaker_user_id IS NOT NULL AND speaker_character_instance_id IS NULL) OR (speaker_type = 'CHARACTER' AND speaker_user_id IS NULL AND speaker_character_instance_id IS NOT NULL) OR (speaker_type = 'SYSTEM' AND speaker_user_id IS NULL AND speaker_character_instance_id IS NULL)", name=op.f('ck_messages_speaker_reference_matches_type')),
    sa.CheckConstraint("input_mode IN ('TEXT', 'VOICE', 'SYSTEM')", name=op.f('ck_messages_input_mode_values')),
    sa.CheckConstraint("speaker_type IN ('USER', 'CHARACTER', 'SYSTEM')", name=op.f('ck_messages_speaker_type_values')),
    sa.CheckConstraint('scene_turn_index IS NULL OR scene_turn_index >= 0', name=op.f('ck_messages_nonnegative_scene_turn_index')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_plan_id'], ['scene_plans.id'], name='fk_messages_scene_plan_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['speaker_character_instance_id'], ['character_instances.id'], name=op.f('fk_messages_speaker_character_instance_id_character_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['speaker_user_id'], ['users.id'], name=op.f('fk_messages_speaker_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('evaluation_items',
    sa.Column('scenario_run_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("feedback_type IN ('DID_WELL', 'TO_IMPROVE')", name=op.f('ck_evaluation_items_feedback_type_values')),
    sa.ForeignKeyConstraint(['scenario_run_id'], ['scenario_runs.id'], name=op.f('fk_evaluation_items_scenario_run_id_scenario_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], name=op.f('fk_evaluation_items_source_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_items')),
    sa.UniqueConstraint('scenario_run_id', 'display_order', name=op.f('uq_evaluation_items_scenario_run_id'))
    )
    op.create_index(op.f('ix_evaluation_items_scenario_run_id'), 'evaluation_items', ['scenario_run_id'], unique=False)
    op.create_table('jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('request_message_id', sa.Uuid(), nullable=False),
    sa.Column('result_message_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='QUEUED', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'REVIEWING', 'COMPLETED', 'RETRYING', 'FAILED', 'CANCELLED')", name=op.f('ck_jobs_status_values')),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_jobs_nonnegative_attempt')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_jobs_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_message_id'], ['messages.id'], name=op.f('fk_jobs_request_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_message_id'], ['messages.id'], name=op.f('fk_jobs_result_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name=op.f('uq_jobs_user_id'))
    )
    op.create_index(op.f('ix_jobs_conversation_id'), 'jobs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_jobs_request_message_id'), 'jobs', ['request_message_id'], unique=False)
    op.create_index('ix_jobs_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('memory_acl',
    sa.Column('memory_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('can_know', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_disclose_to', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("subject_type IN ('USER', 'CHARACTER_INSTANCE')", name=op.f('ck_memory_acl_subject_type_values')),
    sa.CheckConstraint('(NOT can_read OR can_know) AND (NOT can_disclose_to OR can_know)', name=op.f('ck_memory_acl_permission_implications')),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], name=op.f('fk_memory_acl_granted_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_items.id'], name=op.f('fk_memory_acl_memory_id_memory_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id', 'subject_type', 'subject_id', name=op.f('pk_memory_acl'))
    )
    op.create_index('ix_memory_acl_subject', 'memory_acl', ['subject_type', 'subject_id'], unique=False)
    op.create_table('memory_sources',
    sa.Column('memory_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_items.id'], name=op.f('fk_memory_sources_memory_id_memory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_memory_sources_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id', 'message_id', name=op.f('pk_memory_sources'))
    )
    op.create_table('message_segments',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audio_status', sa.String(length=16), nullable=False),
    sa.Column('played_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('audio_storage_uri', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("audio_status IN ('GENERATED', 'QUEUED', 'PLAYING', 'PLAYED', 'DISCARDED', 'CANCELLED')", name=op.f('ck_message_segments_audio_status_values')),
    sa.CheckConstraint('played_ms >= 0', name=op.f('ck_message_segments_nonnegative_played_ms')),
    sa.CheckConstraint('sequence >= 0', name=op.f('ck_message_segments_nonnegative_sequence')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_segments_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_segments')),
    sa.UniqueConstraint('message_id', 'sequence', name=op.f('uq_message_segments_message_id'))
    )
    op.create_index(op.f('ix_message_segments_message_id'), 'message_segments', ['message_id'], unique=False)
    op.create_table('scene_plans',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('triggering_message_id', sa.Uuid(), nullable=False),
    sa.Column('can_ai_speak', sa.Boolean(), nullable=False),
    sa.Column('internal_step_count', sa.Integer(), nullable=False),
    sa.Column('visible_turn_count', sa.Integer(), nullable=False),
    sa.Column('return_turn_to', sa.String(length=16), server_default='USER', nullable=False),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fallback_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("return_turn_to IN ('USER', 'SYSTEM')", name=op.f('ck_scene_plans_return_turn_values')),
    sa.CheckConstraint('internal_step_count BETWEEN 0 AND 5', name=op.f('ck_scene_plans_internal_step_limit')),
    sa.CheckConstraint('visible_turn_count BETWEEN 0 AND 2', name=op.f('ck_scene_plans_visible_turn_limit')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_scene_plans_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggering_message_id'], ['messages.id'], name=op.f('fk_scene_plans_triggering_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_plans'))
    )
    op.create_index(op.f('ix_scene_plans_conversation_id'), 'scene_plans', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_scene_plans_triggering_message_id'), 'scene_plans', ['triggering_message_id'], unique=False)
    op.create_table('job_checkpoints',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_checkpoints_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_checkpoints')),
    sa.UniqueConstraint('job_id', 'step', name=op.f('uq_job_checkpoints_job_id'))
    )
    op.create_index(op.f('ix_job_checkpoints_job_id'), 'job_checkpoints', ['job_id'], unique=False)
    # ### end Alembic commands ###
    op.create_foreign_key(
        "fk_character_templates_current_version_id",
        "character_templates",
        "character_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_messages_scene_plan_id",
        "messages",
        "scene_plans",
        ["scene_plan_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        "fk_messages_scene_plan_id", "messages", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_character_templates_current_version_id",
        "character_templates",
        type_="foreignkey",
    )
    op.drop_table("job_checkpoints")
    op.drop_table("scene_plans")
    op.drop_table("message_segments")
    op.drop_table("memory_sources")
    op.drop_table("memory_acl")
    op.drop_table("jobs")
    op.drop_table("evaluation_items")
    op.drop_table("messages")
    op.drop_table("memory_items")
    op.drop_table("conversation_participants")
    op.drop_table("character_relationships")
    op.drop_table("adaptation_profiles")
    op.drop_table("voice_profiles")
    op.drop_table("scenario_turns")
    op.drop_table("scenario_runs")
    op.drop_table("motion_profiles")
    op.drop_table("character_instances")
    op.drop_table("character_assets")
    op.drop_table("scenario_scenes")
    op.drop_table("scenario_endings")
    op.drop_table("scenario_characters")
    op.drop_table("conversations")
    op.drop_table("character_versions")
    op.drop_table("scenarios")
    op.drop_table("character_templates")
    op.drop_table("assets")
    op.drop_table("users")
